### PR TITLE
Only show stats for the game being played

### PR DESCRIPTION
**Pull request by oxhacks**
(Requires #24)

Only show stats for a game if it is currently the one being played.

### CODE REVIEW

**Comment by arusahni** [comment]
Looks good! Will merge once #24 is in.

**Comment by arusahni** [comment]
@jaykwon there appears to be a merge conflict. Can you fix?

**Comment by oxhacks** [comment]
@arusahni done!

**Comment by arusahni** [comment]
@jaykwon after the merge conflict resolution, this appears to break the team donation progress bar. It seems to be related to the `flex` rules in `.header`. What do you think is the best way forward?

**Comment by oxhacks** [comment]
@arusahni we should go with what works for the progress bar - any smashing of that was unintentional. I don't want to put the burden on you, but if you want to commit it on this branch and merge, I'm OK with that for the sake of simplicity.

Apologies for the break!

**Comment by arusahni** [comment]
@jaykwon 👍

**Pull request merged**
