### PR TITLE
Team donation progress tracker

### PR DESCRIPTION
**Pull request by arusahni**
This is an initial implementation of a team donation progress bar.

screenshot-2017-10-8 humangeo extra life

This MR requires an additional configuration field be added: `TEAM_ID`.  The one for our HG|R team is: `35621`.

I'm also using a lot of ES6 here. This will work in all evergreen browsers, including the current Firefox ESR.  Internet Explorer won't like it, but Edge _should_ be fine.  I understand if this tradeoff is not one we want to make - I was trying to avoid bringing in third party libraries.  If we want to support a wider array of browsers, I can refactor this into something a little more traditional.

Future MR's will bring progress bars for streamers, and presentation improvements (e.g., showing that we've reached our goal, a promoted donation button, etc.).

### CODE REVIEW

**Comment by oxhacks** [comment]
Going to take a look at this. Side note for tracking purposes: !15 shifts the config layout as well as providing an example.

**Comment by oxhacks** [comment]
I really like this, and the code seems clean enough for my taste. The point about Evergreen compatibility is definitely worth noting, though I think for our audience this is probably okay.

Only wish list I would put on this: exposing `fundraisingGoal` on the bar as well somehow. 

Very tasteful! 👍

**Review by dbernard — COMMENTED** [review]
This all looks good. Minor nitpick would be to include the `TEAM_ID` in the README example. As it stands in this PR `TEAM_ID` is now a required config setting. Personally I wouldn't mind if it was optional, but I'm not opposed to merging as is.

**Comment by arusahni** [comment]
@dbernard merged `master` and updated the README.

**Comment by dbernard** [comment]
This is looking awesome! Merging.

**Pull request merged**
